name: elderly_care_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_svg: ^2.0.17
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.12.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  fl_chart: ^0.66.2

  # Vision Guardian
  camera: ^0.10.0+4
  google_mlkit_text_recognition: ^0.13.0  # Offline OCR (mobile only)
  image_picker: ^1.0.7
  js: ^0.6.7  # Required for Tesseract.js web interop

  google_generative_ai: ^0.4.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true