// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCZkurCEujkPfBsXUORO-26fltq2RxEo',
    appId: '1:248030345071:web:c20961ef7f93f2db3a1a9a',
    messagingSenderId: '248030345071',
    projectId: 'buddy-system-74299',
    authDomain: 'buddy-system-74299.firebaseapp.com',
    storageBucket: 'buddy-system-74299.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0A3itpnqCRzuHmn8Lo_paJqao3ENkb4c',
    appId: '1:248030345071:android:56d2eabcbac941d53a1a9a',
    messagingSenderId: '248030345071',
    projectId: 'buddy-system-74299',
    storageBucket: 'buddy-system-74299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzu2TMnwTkPmwBfeDLXDgDvUpGAEw0WfM',
    appId: '1:248030345071:ios:0dadcc30caabaa863a1a9a',
    messagingSenderId: '248030345071',
    projectId: 'buddy-system-74299',
    storageBucket: 'buddy-system-74299.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzu2TMnwTkPmwBfeDLXDgDvUpGAEw0WfM',
    appId: '1:248030345071:ios:0dadcc30caabaa863a1a9a',
    messagingSenderId: '248030345071',
    projectId: 'buddy-system-74299',
    storageBucket: 'buddy-system-74299.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwCZkurCEujkPfBsXUORO-26fltq2RxEo',
    appId: '1:248030345071:web:bd44230d79f2aef23a1a9a',
    messagingSenderId: '248030345071',
    projectId: 'buddy-system-74299',
    authDomain: 'buddy-system-74299.firebaseapp.com',
    storageBucket: 'buddy-system-74299.firebasestorage.app',
  );

}